var partsInfo=[
    {
        name:"容器和布局",
        data:[
                {name:"splitbox",sortPath:"ui",desc:"左右分栏",icon:""},
                {name:"vctrl",sortPath:"ui",desc:"平分宽度",icon:""},
                {name:"movepanel",sortPath:"ui",desc:"移动面板",icon:""},
                {name:"growpanel",sortPath:"ui",desc:"伸展面板",icon:""},
                {name:"panel",sortPath:"ui",desc:"面板",icon:""},
                {name:"tabbox",sortPath:"ui",desc:"标签面板",icon:""},
                {name:"bluebox",sortPath:"ui",desc:"蓝色多行面板",icon:""},
                {name:"sizebox",sortPath:"ui",desc:"大小可变面板",icon:""},
                {name:"swiper",sortPath:"ui",desc:"swiper3.0轮播组件",icon:""},
                {name:"turtlecontrolpanel",sortPath:"ui",desc:"调试器",icon:""},
                {name:"xhr",sortPath:"ui",desc:"xmlhttprequest组件",icon:""}
            ]
    },
    {
        name:"元件和控制",
        data:[
                {name:"button",sortPath:"ui",desc:"按钮",icon:""},
                {name:"colorfont",sortPath:"ui",desc:"多彩文字",icon:""},
                {name:"input",sortPath:"ui",desc:"手机弹出置顶输入框",icon:""},
                {name:"inputbox",sortPath:"ui",desc:"置顶输入框",icon:""},
                {name:"move",sortPath:"ui",desc:"转变内容为移动组件",icon:""},
                {name:"scrollbar",sortPath:"ui",desc:"滚动条",icon:""},
                {name:"timer",sortPath:"ui",desc:"定时器",icon:""},
                {name:"tooltip",sortPath:"ui",desc:"提示信息",icon:""}
            ]
    }
]